name: main

on:  
  push:
    branches: [ jfchin/** ]

env:
  SOLUTION_FILE_PATH: .\workflow-actions\workflow-actions.sln
  
  #TEST_FILE_PATH: .\PLC.Test\bin\Debug\PLC.Test.dll
  
  TEST_LOG_PATH: .\TestResults\*.trx
  
  BUILD_CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Cache nuget packages
      uses: actions/cache@v2
      env:
        cache-name: cache-nuget-packages
      with:
        path: .\packages
        key: ${{ runner.os }}-build-${{ env.cache-packages }}-${{ hashFiles('**/packages.config') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-packages }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      if: steps.cache.outputs.cache-hit != 'true'
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    #- name: Validate Automapper Configs
    #  run: .\PLC.AutoMapperConfigTest\bin\Debug\PLC.AutoMapperConfigTest.exe test
    #- name: Run Tests
    #  run: vstest.console.exe ${{env.TEST_FILE_PATH}} /logger:trx
     
    #- name: Test Report
    #  uses: dorny/test-reporter@v1
    #  if: success() || failure()   
    #  with:
    #    name: MYPLC Tests       
    #    path: ${{env.TEST_LOG_PATH}}
    #    reporter: dotnet-trx   
    #    path-replace-backslashes: 'true'    
